security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: password
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
        user-info-uri: http://localhost:5000/uaa/users/current

server:
  port: 6000

logging:
  level:
    org.springframework.security: DEBUG